apiVersion : apps/v1
kind: Deployment
metadata:
  name: "sanelecluster-3a21"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "sanelecluster-3a21"
  template:
    metadata:
      labels:
        app: "sanelecluster-3a21"
    spec:
      containers:
        - name: "sanelecluster-3a21"
          image: "saneleregistry.azurecr.io/sanelecluster"
          ports:
          - containerPort: 9000