apiVersion: v1
kind: Service
metadata:
    name: "sanelecluster-3a21"
    labels:
        app: "sanelecluster-3a21"
spec:
    type: LoadBalancer
    ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
    selector:
        app: "sanelecluster-3a21"