apiVersion: v1
kind: Service
metadata:
    name: "nodeangcluster-a9cc"
    labels:
        app: "nodeangcluster-a9cc"
spec:
    type: LoadBalancer
    ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
    selector:
        app: "nodeangcluster-a9cc"