on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: saneleregistry.azurecr.io
        username: ${{ secrets.acr_saneleregistry_username }}
        password: ${{ secrets.acr_saneleregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t saneleregistry.azurecr.io/sanelecluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push saneleregistry.azurecr.io/sanelecluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_sanelecluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep saneleclusterba65 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace saneleclusterba65`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: saneleclusterba65
        container-registry-url: saneleregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_saneleregistry_username }}
        container-registry-password: ${{ secrets.acr_saneleregistry_password }}
        secret-name: saneleclustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: saneleclusterba65
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          saneleregistry.azurecr.io/sanelecluster:${{ github.sha }}
        imagepullsecrets: |
          saneleclustedockerauth
